---
- hosts: all
  become: true
  become_user: ansible

  tasks:

    - name: Send sshkey
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"